spring:
  application:
    name: @project.name@
  output:
    ansi.enabled: always
  data:
    mongodb:
      auto-index-creation: false

mongock:
  transactional: false
  migration-scan-package:
    - com.emat.reapi.migrations

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: WARN

springdoc:
  swagger-ui.path: /docs

server:
  port: 8100

app:
  version: @project.version@
  name: @project.name@

prompt:
  analytics: Jesteś analityczką wzorców finansowych,hipnoterapeutką, coachem i mentorką biznesu. Zwróć wyłącznie JSON zgodny ze schematem.
